### ISSUE TITLE
Button Not working

### ISSUE THREAD

**Issue by augmentedme** [rrsaikat/Scientific-Calculator-Calc-#1]
Great Job!!
Some of the calculator buttons are not working.
1. Division button
2. Ans Button
3. root and cube root

and sin, cos and tan are giving negative and wrong values!!
please resolve the issue!!

**Comment by rrsaikat** [comment]
Ok , i will look at it.

**Comment by augmentedme** [comment]
If possible do it soon plz!!

**Comment by rrsaikat** [comment]
This project is now up to date, you can clone it or simply follow this :
1. Ans button ------> 
            *Go to MainActivity.java
            * Add this line into the oncreate method :
                       buttonAnswer.setOnClickListener(this); 
            * Now go to onclick() method & rewrite this elseif logic like this:

![solotion](https://user-images.githubusercontent.com/16695459/49023753-1a2e6e00-f1c2-11e8-8546-a6c73b1fc1a3.png)


2. Division button , root and cube root worked now, you can check it

Thank you.

**Comment by rrsaikat** [comment]
![gif-181126_213844](https://user-images.githubusercontent.com/16695459/49024585-084dca80-f1c4-11e8-8432-4f9278ca3349.gif)


And don't know about the wrong output of sin ,cos , tan operation. Most probably **"JAVA EVALUATOR"** gives the wrong output. Nothing wrong with code.
Suggestion: You can try with another library like "java evaluator".

Happy coding :) @augmentedme
